# Generated by Django 4.2.5 on 2023-10-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('professor', models.CharField(max_length=255)),
                ('data_inicio', models.CharField(max_length=255)),
                ('data_termino', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=255)),
                ('nota', models.CharField(max_length=255)),
                ('data_avaliacao', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='estudante',
            old_name='data',
            new_name='data_de_nascimento',
        ),
        migrations.RenameField(
            model_name='estudante',
            old_name='name',
            new_name='nome',
        ),
    ]
